typography_spectrum: 0.08182
color:
  brandColors:
    - '#ffffff'
    - '#f5be2e'
    - '#000000'
    - '#797979'
    - '#3d3d3d'
  brandStrength: 0.75
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.40655
analytics:
  google: null
  facebook: null
  twitter: null
name: Invoke
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    id: 9b8ff504-0abb-4d97-a9a0-2157f617affb
    type: content
  - name: Work With Us
    id: f9a3915a-21e3-4316-b4f5-2c823057f018
    type: content
favicon: null
title: Telling the Pacific Story
description: Communication Pacific Climate Change Transitions
purpose: []
