name: Invoke
favicon: null
layout_spectrum: 0.40655
typography_spectrum: 0.58417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00223f'
    - '#a6614f'
    - '#d72113'
    - '#d58e47'
    - '#fdf3cf'
  brandStrength: 0.75
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
