name: Invoke
favicon: null
layout_spectrum: 0
typography_spectrum: 0.58417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050503'
    - '#ffffff'
    - '#d6cbb9'
    - '#47361c'
    - '#a17c47'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
