name: Invoke
favicon: null
layout_spectrum: 0.20757027459330857
typography_spectrum: 0.6102344994433224
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.49485420156270266
  lightness: 0.17869194387458265
  saturation: 0.744120308663696
  rhythmicContrast: 0.35440061381086707
purpose: []
