name: Invoke
favicon: null
layout_spectrum: 0.5183
typography_spectrum: 0.58417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0d0c12'
    - '#5c5a5f'
    - '#869099'
    - '#d3d5d2'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
