name: Invoke
favicon: null
layout_spectrum: 0.5183
typography_spectrum: 0.58417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020401'
    - '#a5a695'
    - '#154445'
    - '#366eb7'
    - '#e5f3f6'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
