name: Invoke
favicon: null
layout_spectrum: 0.51156
typography_spectrum: 0.58417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#449694'
    - '#fdfdfd'
    - '#201e23'
    - '#ea0107'
    - '#fbb100'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
