name: Invoke
favicon: null
layout_spectrum: 0.48748
typography_spectrum: 0.58417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7f868c'
    - '#b8b8c4'
    - '#13140e'
    - '#5a5b5d'
    - '#333533'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
