name: Invoke
favicon: null
layout_spectrum: 0.5183
typography_spectrum: 0.58417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#084b8e'
    - '#eb3c48'
    - '#000055'
    - '#ff0000'
    - '#800000'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
