name: Invoke
favicon: null
layout_spectrum: 0.40655
typography_spectrum: 0.08182
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#220000'
    - '#459699'
    - '#e8bc8b'
    - '#a0b184'
    - '#4f4333'
  brandStrength: 0.75
  lightness: 0
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
