name: Invoke
favicon: null
layout_spectrum: 0.40655
typography_spectrum: 0.08182
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f5be2e'
    - '#000000'
    - '#797979'
    - '#3d3d3d'
  brandStrength: 0.75
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
