name: Invoke
favicon: null
layout_spectrum: 0.97391
typography_spectrum: 0.48746
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040203'
    - '#331d20'
    - '#ecadce'
    - '#92444d'
    - '#e3d3fe'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
