name: Invoke
favicon: null
layout_spectrum: 0.38614
typography_spectrum: 0.61585
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#005dc7'
    - '#ffffff'
    - '#090b08'
    - '#588dcc'
    - '#cac8d0'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
