name: Invoke
favicon: null
layout_spectrum: 0.61153
typography_spectrum: 0.48746
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040203'
    - '#331d20'
    - '#ecadce'
    - '#92444d'
    - '#e3d3fe'
  brandStrength: 0.6875
  lightness: 0.17869194387458265
  saturation: 0.744120308663696
  rhythmicContrast: 0.35440061381086707
purpose: []
