name: Invoke
favicon: null
layout_spectrum: 0.20757027459330857
typography_spectrum: 0.48746
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f2'
    - '#7a8692'
    - '#0d1716'
    - '#78a9ba'
    - '#435d5c'
  brandStrength: 0.6875
  lightness: 0.17869194387458265
  saturation: 0.744120308663696
  rhythmicContrast: 0.35440061381086707
purpose: []
