name: Invoke
favicon: null
layout_spectrum: 0.40655
typography_spectrum: 0.58417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cfdbea'
    - '#4f9ed7'
    - '#1c1e22'
    - '#534d41'
    - '#d63614'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
